version: "3.7"

services:
  app:
    build: .
    container_name: spring_boot_app
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/testing
      SPRING_DATASOURCE_USERNAME: samuel         # Matches MYSQL_USER
      SPRING_DATASOURCE_PASSWORD: 1234     # Matches MYSQL_PASSWORD
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    ports:
      - 3306:3306
    networks:
      - app_network
    environment:
      MYSQL_DATABASE: testing          # Database name
      MYSQL_USER: samuel               # Username for the Spring Boot app
      MYSQL_PASSWORD: 1234        # Password for the Spring Boot app
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

networks:
  app_network:

volumes:
  db_data:
